export default {
  login: "Souvik-Nayak",
  id: 60834400,
  node_id: "MDQ6VXNlcjYwODM0NDAw",
  avatar_url: "https://avatars.githubusercontent.com/u/60834400?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Souvik-Nayak",
  html_url: "https://github.com/Souvik-Nayak",
  followers_url: "https://api.github.com/users/Souvik-Nayak/followers",
  following_url: "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
  gists_url: "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Souvik-Nayak/subscriptions",
  organizations_url: "https://api.github.com/users/Souvik-Nayak/orgs",
  repos_url: "https://api.github.com/users/Souvik-Nayak/repos",
  events_url: "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
  received_events_url: "https://api.github.com/users/Souvik-Nayak/received_events",
  type: "User",
  site_admin: false,
  name: "Souvik Nayak",
  company: null,
  blog: "",
  location: "India",
  email: null,
  hireable: null,
  bio: "MERN | MEAN Developer",
  twitter_username: null,
  public_repos: 14,
  public_gists: 0,
  followers: 17,
  following: 20,
  created_at: "2020-02-09T03:58:43Z",
  updated_at: "2022-07-21T16:50:14Z"
};
