export default [
  {
    "id": 420803129,
    "node_id": "R_kgDOGRTyOQ",
    "name": "angular-material-calculator",
    "full_name": "Souvik-Nayak/angular-material-calculator",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/angular-material-calculator",
    "description": "⌛ A calculator app built with Angular and Angular Material components.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/angular-material-calculator/deployments",
    "created_at": "2021-10-24T21:45:01Z",
    "updated_at": "2021-11-15T11:40:24Z",
    "pushed_at": "2021-11-15T11:40:21Z",
    "git_url": "git://github.com/Souvik-Nayak/angular-material-calculator.git",
    "ssh_url": "git@github.com:Souvik-Nayak/angular-material-calculator.git",
    "clone_url": "https://github.com/Souvik-Nayak/angular-material-calculator.git",
    "svn_url": "https://github.com/Souvik-Nayak/angular-material-calculator",
    "homepage": "",
    "size": 199,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "angular",
      "angularcomponent",
      "angularmaterial",
      "calculator",
      "example-project",
      "typescript"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 283549999,
    "node_id": "MDEwOlJlcG9zaXRvcnkyODM1NDk5OTk=",
    "name": "bmi-calculator",
    "full_name": "Souvik-Nayak/bmi-calculator",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/bmi-calculator",
    "description": "🎵 An Web App that takes the user's weight(kg) and height(feet-inch) and returns the BMI value with a comment. BMI can be used to screen for weight categories that may lead to health problems but it is not diagnostic of the body fatness or health of an individual.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/bmi-calculator/deployments",
    "created_at": "2020-07-29T16:34:06Z",
    "updated_at": "2021-11-01T11:31:15Z",
    "pushed_at": "2021-07-20T12:08:06Z",
    "git_url": "git://github.com/Souvik-Nayak/bmi-calculator.git",
    "ssh_url": "git@github.com:Souvik-Nayak/bmi-calculator.git",
    "clone_url": "https://github.com/Souvik-Nayak/bmi-calculator.git",
    "svn_url": "https://github.com/Souvik-Nayak/bmi-calculator",
    "homepage": "https://souvik-nayak.github.io/bmi-calculator/",
    "size": 20,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "css3",
      "html5",
      "vanilla-js"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 418568343,
    "node_id": "R_kgDOGPLYlw",
    "name": "calculator",
    "full_name": "Souvik-Nayak/calculator",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/calculator",
    "description": "📲A simple calculator built with Angular. It features BODMAS functions as well as Prime & Factorial algorithms.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/calculator",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/calculator/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/calculator/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/calculator/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/calculator/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/calculator/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/calculator/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/calculator/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/calculator/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/calculator/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/calculator/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/calculator/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/calculator/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/calculator/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/calculator/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/calculator/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/calculator/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/calculator/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/calculator/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/calculator/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/calculator/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/calculator/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/calculator/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/calculator/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/calculator/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/calculator/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/calculator/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/calculator/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/calculator/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/calculator/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/calculator/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/calculator/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/calculator/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/calculator/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/calculator/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/calculator/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/calculator/deployments",
    "created_at": "2021-10-18T15:48:03Z",
    "updated_at": "2021-11-01T11:23:34Z",
    "pushed_at": "2021-11-01T10:23:52Z",
    "git_url": "git://github.com/Souvik-Nayak/calculator.git",
    "ssh_url": "git@github.com:Souvik-Nayak/calculator.git",
    "clone_url": "https://github.com/Souvik-Nayak/calculator.git",
    "svn_url": "https://github.com/Souvik-Nayak/calculator",
    "homepage": "",
    "size": 135,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "angular",
      "angularcomponent",
      "calculator",
      "example-project",
      "html",
      "typescript"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 411956880,
    "node_id": "R_kgDOGI32kA",
    "name": "coronavirus-tracker",
    "full_name": "Souvik-Nayak/coronavirus-tracker",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/coronavirus-tracker",
    "description": "⌛ A Covid-19 cases tracking Web app built for learning purposes. This app uses Covid public API to fetch the relevant covid cases data about the searched country. If the user visits the searched country covid details it shows the visited country details data.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/coronavirus-tracker/deployments",
    "created_at": "2021-09-30T06:58:21Z",
    "updated_at": "2021-11-01T10:19:53Z",
    "pushed_at": "2021-09-30T11:47:47Z",
    "git_url": "git://github.com/Souvik-Nayak/coronavirus-tracker.git",
    "ssh_url": "git@github.com:Souvik-Nayak/coronavirus-tracker.git",
    "clone_url": "https://github.com/Souvik-Nayak/coronavirus-tracker.git",
    "svn_url": "https://github.com/Souvik-Nayak/coronavirus-tracker",
    "homepage": "https://covwatch-19.herokuapp.com/",
    "size": 6639,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "apexcharts",
      "api",
      "chart",
      "covid-19",
      "covid-data",
      "covid-tracker",
      "framer-motion",
      "html",
      "javascript",
      "npm",
      "pandemic",
      "react",
      "tailwindcss"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 454663725,
    "node_id": "R_kgDOGxmeLQ",
    "name": "forum2k-devathon-2022",
    "full_name": "Souvik-Nayak/forum2k-devathon-2022",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/forum2k-devathon-2022",
    "description": "✈️ Developed a Web App for the Forum2k Hackathon using MERN Stack included CRUD operations",
    "fork": true,
    "url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/forum2k-devathon-2022/deployments",
    "created_at": "2022-02-02T06:15:05Z",
    "updated_at": "2022-02-08T18:16:30Z",
    "pushed_at": "2022-02-08T18:04:47Z",
    "git_url": "git://github.com/Souvik-Nayak/forum2k-devathon-2022.git",
    "ssh_url": "git@github.com:Souvik-Nayak/forum2k-devathon-2022.git",
    "clone_url": "https://github.com/Souvik-Nayak/forum2k-devathon-2022.git",
    "svn_url": "https://github.com/Souvik-Nayak/forum2k-devathon-2022",
    "homepage": "",
    "size": 11946,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "ant",
      "axios",
      "express",
      "framer-motion",
      "gasp",
      "jsx",
      "material-ui",
      "mongodb",
      "nodejs",
      "react",
      "react-router"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 493200636,
    "node_id": "R_kgDOHWWk_A",
    "name": "GitHubGraduation-2022",
    "full_name": "Souvik-Nayak/GitHubGraduation-2022",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/GitHubGraduation-2022",
    "description": "Join the GitHub Graduation Yearbook and \"walk the stage\" on June 11.",
    "fork": true,
    "url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/GitHubGraduation-2022/deployments",
    "created_at": "2022-05-17T10:23:03Z",
    "updated_at": "2022-05-17T10:27:02Z",
    "pushed_at": "2022-05-17T10:26:56Z",
    "git_url": "git://github.com/Souvik-Nayak/GitHubGraduation-2022.git",
    "ssh_url": "git@github.com:Souvik-Nayak/GitHubGraduation-2022.git",
    "clone_url": "https://github.com/Souvik-Nayak/GitHubGraduation-2022.git",
    "svn_url": "https://github.com/Souvik-Nayak/GitHubGraduation-2022",
    "homepage": "",
    "size": 53045,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 387949682,
    "node_id": "MDEwOlJlcG9zaXRvcnkzODc5NDk2ODI=",
    "name": "GPA-Scraper",
    "full_name": "Souvik-Nayak/GPA-Scraper",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/GPA-Scraper",
    "description": "⚡️ A Web Scrapper built on Python and Selenium to extract the result of students in a systematic manner and maintaing high-end backups.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/GPA-Scraper/deployments",
    "created_at": "2021-07-21T00:45:02Z",
    "updated_at": "2021-11-01T10:17:44Z",
    "pushed_at": "2021-10-28T07:29:31Z",
    "git_url": "git://github.com/Souvik-Nayak/GPA-Scraper.git",
    "ssh_url": "git@github.com:Souvik-Nayak/GPA-Scraper.git",
    "clone_url": "https://github.com/Souvik-Nayak/GPA-Scraper.git",
    "svn_url": "https://github.com/Souvik-Nayak/GPA-Scraper",
    "homepage": "",
    "size": 5,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Python",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "beautifulsoup4",
      "json",
      "selenium"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main"
  },
  {
    "id": 427908053,
    "node_id": "R_kgDOGYFb1Q",
    "name": "httpclient-routing-angular",
    "full_name": "Souvik-Nayak/httpclient-routing-angular",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/httpclient-routing-angular",
    "description": "💻 A todo application with list , details and API integration built using HttpClient and Routing in Angular.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/httpclient-routing-angular/deployments",
    "created_at": "2021-11-14T11:19:37Z",
    "updated_at": "2021-11-15T18:47:08Z",
    "pushed_at": "2021-11-15T11:43:10Z",
    "git_url": "git://github.com/Souvik-Nayak/httpclient-routing-angular.git",
    "ssh_url": "git@github.com:Souvik-Nayak/httpclient-routing-angular.git",
    "clone_url": "https://github.com/Souvik-Nayak/httpclient-routing-angular.git",
    "svn_url": "https://github.com/Souvik-Nayak/httpclient-routing-angular",
    "homepage": "",
    "size": 5145,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "angular",
      "angular-component",
      "angular-service",
      "example-project",
      "html",
      "httpclient",
      "routing",
      "typescript"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 393943228,
    "node_id": "MDEwOlJlcG9zaXRvcnkzOTM5NDMyMjg=",
    "name": "Lets-Grow-More",
    "full_name": "Souvik-Nayak/Lets-Grow-More",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/Lets-Grow-More",
    "description": "⚡️ Let's Grow More Virtual Internship Programme for September 2021 on the topic of Web Development. This repository has all my tasks thats I have completed the Lets Grow More's Virtual Internship Program.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/Lets-Grow-More/deployments",
    "created_at": "2021-08-08T11:37:37Z",
    "updated_at": "2021-11-01T10:15:26Z",
    "pushed_at": "2021-09-30T11:48:06Z",
    "git_url": "git://github.com/Souvik-Nayak/Lets-Grow-More.git",
    "ssh_url": "git@github.com:Souvik-Nayak/Lets-Grow-More.git",
    "clone_url": "https://github.com/Souvik-Nayak/Lets-Grow-More.git",
    "svn_url": "https://github.com/Souvik-Nayak/Lets-Grow-More",
    "homepage": "",
    "size": 98189,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "bootstrap",
      "createjs",
      "css",
      "html",
      "javascript",
      "react"
    ],
    "visibility": "public",
    "forks": 1,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 434338526,
    "node_id": "R_kgDOGeN63g",
    "name": "library-backend-mongodb",
    "full_name": "Souvik-Nayak/library-backend-mongodb",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/library-backend-mongodb",
    "description": "✨ Backend Application using HTTP Routing in AngularJS",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/library-backend-mongodb/deployments",
    "created_at": "2021-12-02T18:52:43Z",
    "updated_at": "2022-02-08T18:08:20Z",
    "pushed_at": "2021-12-02T18:54:01Z",
    "git_url": "git://github.com/Souvik-Nayak/library-backend-mongodb.git",
    "ssh_url": "git@github.com:Souvik-Nayak/library-backend-mongodb.git",
    "clone_url": "https://github.com/Souvik-Nayak/library-backend-mongodb.git",
    "svn_url": "https://github.com/Souvik-Nayak/library-backend-mongodb",
    "homepage": "",
    "size": 2890,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "angular",
      "backend-api",
      "http-routing",
      "mongodb-atlas",
      "npm-package"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 389723277,
    "node_id": "MDEwOlJlcG9zaXRvcnkzODk3MjMyNzc=",
    "name": "netflix-clone",
    "full_name": "Souvik-Nayak/netflix-clone",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/netflix-clone",
    "description": "💻 A Netflix clone built using modern React tools/best practices, such as hooks, context API, and redux toolkit. This project is a simplified front end clone of Netflix. It uses The MovieDB Api.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/netflix-clone/deployments",
    "created_at": "2021-07-26T17:56:17Z",
    "updated_at": "2021-11-01T10:16:34Z",
    "pushed_at": "2021-09-30T12:30:56Z",
    "git_url": "git://github.com/Souvik-Nayak/netflix-clone.git",
    "ssh_url": "git@github.com:Souvik-Nayak/netflix-clone.git",
    "clone_url": "https://github.com/Souvik-Nayak/netflix-clone.git",
    "svn_url": "https://github.com/Souvik-Nayak/netflix-clone",
    "homepage": "https://netflix-6bb19.web.app/",
    "size": 420,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "api",
      "chartjs",
      "express",
      "firebase",
      "html",
      "reactjs",
      "redux",
      "styled-components"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main"
  },
  {
    "id": 427631639,
    "node_id": "R_kgDOGX0kFw",
    "name": "services-angular-todo",
    "full_name": "Souvik-Nayak/services-angular-todo",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/services-angular-todo",
    "description": "🎀 A todo list and details app built using Services in Angular.",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/services-angular-todo/deployments",
    "created_at": "2021-11-13T10:17:14Z",
    "updated_at": "2021-11-14T11:43:29Z",
    "pushed_at": "2021-11-14T11:34:40Z",
    "git_url": "git://github.com/Souvik-Nayak/services-angular-todo.git",
    "ssh_url": "git@github.com:Souvik-Nayak/services-angular-todo.git",
    "clone_url": "https://github.com/Souvik-Nayak/services-angular-todo.git",
    "svn_url": "https://github.com/Souvik-Nayak/services-angular-todo",
    "homepage": "",
    "size": 330,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "angular",
      "angular-component",
      "angular-services",
      "css",
      "example-project",
      "html",
      "typescript"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 390366898,
    "node_id": "MDEwOlJlcG9zaXRvcnkzOTAzNjY4OTg=",
    "name": "Souvik-Nayak",
    "full_name": "Souvik-Nayak/Souvik-Nayak",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/Souvik-Nayak",
    "description": "⌛ Github README",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/Souvik-Nayak/deployments",
    "created_at": "2021-07-28T13:46:14Z",
    "updated_at": "2022-02-14T15:47:10Z",
    "pushed_at": "2022-06-30T18:25:32Z",
    "git_url": "git://github.com/Souvik-Nayak/Souvik-Nayak.git",
    "ssh_url": "git@github.com:Souvik-Nayak/Souvik-Nayak.git",
    "clone_url": "https://github.com/Souvik-Nayak/Souvik-Nayak.git",
    "svn_url": "https://github.com/Souvik-Nayak/Souvik-Nayak",
    "homepage": "",
    "size": 267,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 387771555,
    "node_id": "MDEwOlJlcG9zaXRvcnkzODc3NzE1NTU=",
    "name": "weatherify",
    "full_name": "Souvik-Nayak/weatherify",
    "private": false,
    "owner": {
      "login": "Souvik-Nayak",
      "id": 60834400,
      "node_id": "MDQ6VXNlcjYwODM0NDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/60834400?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Souvik-Nayak",
      "html_url": "https://github.com/Souvik-Nayak",
      "followers_url": "https://api.github.com/users/Souvik-Nayak/followers",
      "following_url": "https://api.github.com/users/Souvik-Nayak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Souvik-Nayak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Souvik-Nayak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Souvik-Nayak/subscriptions",
      "organizations_url": "https://api.github.com/users/Souvik-Nayak/orgs",
      "repos_url": "https://api.github.com/users/Souvik-Nayak/repos",
      "events_url": "https://api.github.com/users/Souvik-Nayak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Souvik-Nayak/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Souvik-Nayak/weatherify",
    "description": "🚀 Weather Forecast App using Reactjs and APIs. It let you know Temperature, Humidity and Conditions of any places in the world in Real Time and graphically present the geographical conditions with +GMT standard",
    "fork": false,
    "url": "https://api.github.com/repos/Souvik-Nayak/weatherify",
    "forks_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/forks",
    "keys_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/teams",
    "hooks_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/hooks",
    "issue_events_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/events",
    "assignees_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/tags",
    "blobs_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/languages",
    "stargazers_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/stargazers",
    "contributors_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/contributors",
    "subscribers_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/subscribers",
    "subscription_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/subscription",
    "commits_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/merges",
    "archive_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/downloads",
    "issues_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/labels{/name}",
    "releases_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Souvik-Nayak/weatherify/deployments",
    "created_at": "2021-07-20T11:37:19Z",
    "updated_at": "2021-11-01T10:18:45Z",
    "pushed_at": "2021-09-30T11:47:08Z",
    "git_url": "git://github.com/Souvik-Nayak/weatherify.git",
    "ssh_url": "git@github.com:Souvik-Nayak/weatherify.git",
    "clone_url": "https://github.com/Souvik-Nayak/weatherify.git",
    "svn_url": "https://github.com/Souvik-Nayak/weatherify",
    "homepage": "https://weather-app-e97.netlify.app/",
    "size": 393,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "expressjs",
      "html",
      "nodejs",
      "react",
      "styled-components"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  }
]